project:
  name: "CrediAS"
  description: "Credit Assessment System"
  type: "fullstack"
  version: "1.0.0"

bmad:
  core-version: "4.29.0"
  installation-date: "2025-01-18"
  
agents:
  preferred-team: "fullstack"
  active-agents:
    - analyst
    - pm
    - architect
    - dev
    - qa
    - sm
    - ux-expert
    - po
    - bmad-orchestrator
    - bmad-master

workflow:
  default: "greenfield-fullstack"
  story-template: "story-tmpl.yaml"
  
development:
  tdd: true
  code-review: true
  documentation: true
  
paths:
  core: ".bmad-core"
  stories: "stories"
  docs: "docs"
  templates: ".bmad-core/templates"
  
ide:
  type: "claude-code"
  commands-path: ".claude/commands/BMad"
  
figma:
  url: "https://www.figma.com/design/lXKZe15q21LAnhgKfvO4uN/CrediAS?node-id=2002-6913&t=JUxpHNQAbfawUrZr-1"
  
expansion-packs: []